/* Playable nations added after world.js. Belgium/Turkey/Scotland were clubOnly. */
NATIONS = NATIONS.concat([
  { id: "sct", name: "Escócia", adj: "Escocês", conf: "uefa", ntCut: -4, flag: "img/flags/sct.png" },
  { id: "be", name: "Bélgica", adj: "Belga", conf: "uefa", ntCut: -3, flag: "img/flags/be.png" },
  { id: "tr", name: "Turquia", adj: "Turco", conf: "uefa", ntCut: -4, flag: "img/flags/tr.png" },
  { id: "cl", name: "Chile", adj: "Chileno", conf: "conmebol", ntCut: -3, flag: "img/flags/cl.png" },
  { id: "ec", name: "Equador", adj: "Equatoriano", conf: "conmebol", ntCut: -5, flag: "img/flags/ec.png" },
  { id: "py", name: "Paraguai", adj: "Paraguaio", conf: "conmebol", ntCut: -5, flag: "img/flags/py.png" },
  { id: "hr", name: "Croácia", adj: "Croata", conf: "uefa", ntCut: -1, flag: "img/flags/hr.png" },
  { id: "gr", name: "Grécia", adj: "Grego", conf: "uefa", ntCut: -4, flag: "img/flags/gr.png" },
  { id: "ru", name: "Rússia", adj: "Russo", conf: "uefa", ntCut: -3, flag: "img/flags/ru.png" },
  { id: "ma", name: "Marrocos", adj: "Marroquino", conf: "caf", ntCut: -4, flag: "img/flags/ma.png" },
  { id: "kr", name: "Coreia do Sul", adj: "Sul-coreano", conf: "afc", ntCut: -5, flag: "img/flags/kr.png" },
  { id: "ca", name: "Canadá", adj: "Canadense", conf: "concacaf", ntCut: -6, flag: "img/flags/ca.png" },
  { id: "dk", name: "Dinamarca", adj: "Dinamarquês", conf: "uefa", ntCut: -2, flag: "img/flags/dk.png" },
  { id: "se", name: "Suécia", adj: "Sueco", conf: "uefa", ntCut: -3, flag: "img/flags/se.png" },
  { id: "no", name: "Noruega", adj: "Norueguês", conf: "uefa", ntCut: -4, flag: "img/flags/no.png" },
  { id: "sa", name: "Arábia Saudita", adj: "Saudita", conf: "afc", ntCut: -4, flag: "img/flags/sa.png" },
  { id: "eg", name: "Egito", adj: "Egípcio", conf: "caf", ntCut: -3, flag: "img/flags/eg.png" },
  { id: "dz", name: "Argélia", adj: "Argelino", conf: "caf", ntCut: -4, flag: "img/flags/dz.png" },
  { id: "tn", name: "Tunísia", adj: "Tunisiano", conf: "caf", ntCut: -5, flag: "img/flags/tn.png" },
  { id: "qa", name: "Catar", adj: "Catarense", conf: "afc", ntCut: -5, flag: "img/flags/qa.png" },
  { id: "ae", name: "Emirados Árabes", adj: "Emiratense", conf: "afc", ntCut: -6, flag: "img/flags/ae.png" }
]);

/* LEAGUE_SEASON placements: Brasileirão 2026 + EUR 2026/27 — see LEAGUE_SEASON in world.js */
LEAGUES = LEAGUES.concat([
  { id: "bel", name: "Pro League", nation: "be", tier: 1, level: 3.6, continental: "ucl", size: 18, trophy: "proleague", logo: "img/leagues/bel.png", color: "#FFD700" },
  { id: "tur", name: "Süper Lig", nation: "tr", tier: 1, level: 3.7, continental: "ucl", size: 18, trophy: "superlig", logo: "img/leagues/tur.png", color: "#E30A17" },
  { id: "sco", name: "Premiership", nation: "sct", tier: 1, level: 3.3, continental: "ucl", size: 12, trophy: "scottish", logo: "img/leagues/sco.png", color: "#005EB8" },
  { id: "chi", name: "Campeonato Nacional", nation: "cl", tier: 1, level: 3.2, continental: "lib", size: 16, trophy: "primera_cl", logo: "img/leagues/chi.png", color: "#0039A6" },
  { id: "ecu", name: "LigaPro Serie A", nation: "ec", tier: 1, level: 2.9, continental: "lib", size: 16, trophy: "liga_ec", logo: "img/leagues/ecu.png", color: "#FFD100" },
  { id: "par", name: "Primera División", nation: "py", tier: 1, level: 2.8, continental: "lib", size: 12, trophy: "primera_py", logo: "img/leagues/par.png", color: "#D52B1E" },
  { id: "hnl", name: "HNL", nation: "hr", tier: 1, level: 3.3, continental: "ucl", size: 10, trophy: "hnl", logo: "img/leagues/hnl.png", color: "#FF0000" },
  { id: "slg", name: "Super League Greece", nation: "gr", tier: 1, level: 3.2, continental: "ucl", size: 14, trophy: "slgreece", logo: "img/leagues/slg.png", color: "#0D5EAF" },
  { id: "rpl", name: "Russian Premier League", nation: "ru", tier: 1, level: 3.5, continental: "ucl", size: 16, trophy: "rpl", logo: "img/leagues/rpl.png", color: "#E4181C" },
  { id: "bot", name: "Botola Pro", nation: "ma", tier: 1, level: 2.6, continental: "caf", size: 16, trophy: "botola", logo: "img/leagues/bot.png", color: "#C1272D" },
  { id: "kle", name: "K League 1", nation: "kr", tier: 1, level: 3.1, continental: "acl", size: 12, trophy: "kleague", logo: "img/leagues/kle.png", color: "#E8342A" },
  { id: "cpl", name: "Canadian Premier League", nation: "ca", tier: 1, level: 2.7, continental: "concacaf", size: 8, trophy: "cpl", logo: "img/leagues/cpl.png", color: "#E4002B" },
  { id: "dsl", name: "Danish Superliga", nation: "dk", tier: 1, level: 3.6, continental: "ucl", size: 12, trophy: "dsliga", logo: "img/leagues/dsl.png", color: "#C60C30" },
  { id: "all", name: "Allsvenskan", nation: "se", tier: 1, level: 3.4, continental: "ucl", size: 16, trophy: "allsvenskan", logo: "img/leagues/all.png", color: "#006AA7" },
  { id: "eli", name: "Eliteserien", nation: "no", tier: 1, level: 3.4, continental: "ucl", size: 16, trophy: "eliteserien", logo: "img/leagues/eli.png", color: "#BA0C2F" },
  { id: "spl", name: "Saudi Pro League", nation: "sa", tier: 1, level: 3.6, continental: "acl", size: 18, trophy: "spl", logo: "img/leagues/spl.png", color: "#006C35" },
  { id: "epl", name: "Egyptian Premier League", nation: "eg", tier: 1, level: 3.4, continental: "caf", size: 20, trophy: "epl", logo: "img/leagues/epl.png", color: "#C8102E" },
  { id: "alg", name: "Algerian Ligue 1", nation: "dz", tier: 1, level: 3.1, continental: "caf", size: 16, trophy: "alg1", logo: "img/leagues/alg.png", color: "#006233" },
  { id: "tun", name: "Tunisian Ligue 1", nation: "tn", tier: 1, level: 3.1, continental: "caf", size: 16, trophy: "tun1", logo: "img/leagues/tun.png", color: "#E70013" },
  { id: "qsl", name: "Qatar Stars League", nation: "qa", tier: 1, level: 3.3, continental: "acl", size: 12, trophy: "qsl", logo: "img/leagues/qsl.png", color: "#8A1538" },
  { id: "uae", name: "UAE Pro League", nation: "ae", tier: 1, level: 3.2, continental: "acl", size: 14, trophy: "uaepl", logo: "img/leagues/uae.png", color: "#00732F" }
]);

function _xc(id, name, city, nation, leagueId, level, c1, c2) {
  return {
    id: id, name: name, city: city, nation: nation, leagueId: leagueId, level: level,
    colors: [c1, c2, c1], pattern: "solid", charge: "star", youth: true,
    crest: "img/clubs/" + id + ".png"
  };
}

CLUBS = CLUBS.concat([
  _xc("avl", "Aston Villa", "Birmingham", "en", "eng", 4.2, "#670E36", "#94BEE5"),
  _xc("whu", "West Ham", "Londres", "en", "eng2", 3.4, "#7A263A", "#1BB1E7"),
  _xc("bha", "Brighton", "Brighton", "en", "eng", 4.0, "#0057B8", "#FFFFFF"),
  _xc("eve", "Everton", "Liverpool", "en", "eng", 3.8, "#003399", "#FFFFFF"),
  _xc("cry", "Crystal Palace", "Londres", "en", "eng", 3.8, "#1B458F", "#C4122E"),
  _xc("ful", "Fulham", "Londres", "en", "eng", 3.8, "#000000", "#FFFFFF"),
  _xc("wol", "Wolves", "Wolverhampton", "en", "eng2", 3.3, "#FDB913", "#111111"),
  _xc("nfo", "Nottingham Forest", "Nottingham", "en", "eng", 3.9, "#DD0000", "#FFFFFF"),
  _xc("ath", "Athletic Bilbao", "Bilbao", "es", "esp", 4.1, "#EE2523", "#FFFFFF"),
  _xc("val", "Valencia", "Valência", "es", "esp2", 3.4, "#EEEEEE", "#D50032"),
  _xc("bet", "Betis", "Sevilha", "es", "esp", 3.9, "#00954C", "#FFFFFF"),
  _xc("celv", "Celta", "Vigo", "es", "esp2", 3.2, "#8AC3E8", "#FFFFFF"),
  _xc("ata", "Atalanta", "Bérgamo", "it", "ita", 4.2, "#1E71B8", "#000000"),
  _xc("fio", "Fiorentina", "Florença", "it", "ita", 4.0, "#482E92", "#FFFFFF"),
  _xc("bol", "Bologna", "Bolonha", "it", "ita2", 3.3, "#A20A28", "#1A1A6C"),
  _xc("tor", "Torino", "Turim", "it", "ita2", 3.2, "#8B1A1A", "#FFFFFF"),
  _xc("espy", "Espanyol", "Barcelona", "es", "esp2", 3.3, "#1E5AA8", "#FFFFFF"),
  _xc("elc", "Elche", "Elche", "es", "esp2", 3.0, "#FFFFFF", "#007A33"),
  _xc("levt", "Levante", "Valência", "es", "esp2", 3.1, "#B5003C", "#0057A8"),
  _xc("vll", "Valladolid", "Valladolid", "es", "esp2", 3.0, "#6C1D45", "#FFFFFF"),
  _xc("plrm", "Palermo", "Palermo", "it", "ita2", 3.1, "#FFD100", "#E30613"),
  _xc("bari", "Bari", "Bari", "it", "ita2", 3.0, "#FFFFFF", "#E30613"),
  _xc("cre", "Cremonese", "Cremona", "it", "ita2", 2.9, "#E30613", "#999999"),
  _xc("parm", "Parma", "Parma", "it", "ita2", 3.2, "#FFE200", "#0033A0"),
  _xc("wlf", "Wolfsburg", "Wolfsburg", "de", "ger2", 3.2, "#65B32E", "#FFFFFF"),
  _xc("bmg", "Gladbach", "Mönchengladbach", "de", "ger", 3.8, "#000000", "#FFFFFF"),
  _xc("fre", "Freiburg", "Freiburg", "de", "ger", 3.8, "#000000", "#E30613"),
  _xc("hof", "Hoffenheim", "Sinsheim", "de", "ger", 3.7, "#1C63B7", "#FFFFFF"),
  _xc("renn", "Rennes", "Rennes", "fr", "fra", 3.8, "#E20E0E", "#000000"),
  _xc("len", "Lens", "Lens", "fr", "fra", 3.8, "#E30613", "#FCDD09"),
  _xc("str", "Strasbourg", "Estrasburgo", "fr", "fra", 3.6, "#009FE3", "#E30613"),
  _xc("nte", "Nantes", "Nantes", "fr", "fra2", 2.9, "#FFE200", "#00A651"),
  _xc("bra", "Braga", "Braga", "pt", "por", 3.8, "#E30613", "#FFFFFF"),
  _xc("vgu", "Vitória Guimarães", "Guimarães", "pt", "por", 3.4, "#FFFFFF", "#000000"),
  _xc("az", "AZ Alkmaar", "Alkmaar", "nl", "ned", 3.6, "#ED1C24", "#FFFFFF"),
  _xc("twt", "Twente", "Enschede", "nl", "ned", 3.5, "#E2001A", "#FFFFFF"),
  _xc("utr", "Utrecht", "Utrecht", "nl", "ned", 3.4, "#E10600", "#FFFFFF"),
  _xc("hee", "Heerenveen", "Heerenveen", "nl", "ned", 3.3, "#0057A8", "#FFFFFF"),
  _xc("nec", "NEC", "Nijmegen", "nl", "ned", 3.2, "#E30613", "#009640"),
  _xc("gae", "Go Ahead Eagles", "Deventer", "nl", "ned", 3.2, "#FFD100", "#C8102E"),
  _xc("gro", "Groningen", "Groningen", "nl", "ned", 3.1, "#009640", "#FFFFFF"),
  _xc("spa", "Sparta", "Rotterdam", "nl", "ned", 3.1, "#C8102E", "#FFFFFF"),
  _xc("zwl", "PEC Zwolle", "Zwolle", "nl", "ned", 3.0, "#0077C8", "#FFFFFF"),
  _xc("fos", "Fortuna Sittard", "Sittard", "nl", "ned", 3.0, "#FFD100", "#007A33"),
  _xc("exc", "Excelsior", "Rotterdam", "nl", "ned", 2.9, "#111111", "#E30613"),
  _xc("ado", "ADO Den Haag", "Den Haag", "nl", "ned", 2.9, "#FFD100", "#007A33"),
  _xc("wil", "Willem II", "Tilburg", "nl", "ned", 2.9, "#C8102E", "#0033A0"),
  _xc("cbu", "Cambuur", "Leeuwarden", "nl", "ned", 2.8, "#FFD100", "#111111"),
  _xc("tel", "Telstar", "IJmuiden", "nl", "ned", 2.7, "#FFD100", "#0033A0"),
  _xc("clb", "Club Brugge", "Bruges", "be", "bel", 3.9, "#0070B8", "#000000"),
  _xc("and", "Anderlecht", "Bruxelas", "be", "bel", 3.5, "#5A2D81", "#FFFFFF"),
  _xc("gal", "Galatasaray", "Istambul", "tr", "tur", 3.9, "#FDB912", "#A32521"),
  _xc("fen", "Fenerbahçe", "Istambul", "tr", "tur", 3.8, "#002F6C", "#FFED00"),
  _xc("cel", "Celtic", "Glasgow", "sct", "sco", 3.6, "#018749", "#FFFFFF"),
  _xc("ran", "Rangers", "Glasgow", "sct", "sco", 3.6, "#054C9E", "#FFFFFF"),
  _xc("gnk", "Genk", "Genk", "be", "bel", 3.6, "#1B4F9C", "#FFFFFF"),
  _xc("bjk", "Beşiktaş", "Istambul", "tr", "tur", 3.7, "#000000", "#FFFFFF"),
  _xc("abd", "Aberdeen", "Aberdeen", "sct", "sco", 3.2, "#E30613", "#FFFFFF"),
  _xc("cco", "Colo-Colo", "Santiago", "cl", "chi", 3.5, "#FFFFFF", "#000000"),
  _xc("ude", "Universidad de Chile", "Santiago", "cl", "chi", 3.3, "#0033A0", "#FFFFFF"),
  _xc("ucat", "Universidad Católica", "Santiago", "cl", "chi", 3.3, "#0033A0", "#FFFFFF"),
  _xc("bsc", "Barcelona SC", "Guayaquil", "ec", "ecu", 3.0, "#FFD100", "#0033A0"),
  _xc("ldu", "LDU Quito", "Quito", "ec", "ecu", 3.1, "#FFFFFF", "#0033A0"),
  _xc("eme", "Emelec", "Guayaquil", "ec", "ecu", 2.9, "#0033A0", "#FFFFFF"),
  _xc("olp", "Olimpia", "Assunção", "py", "par", 3.1, "#FFFFFF", "#000000"),
  _xc("cpo", "Cerro Porteño", "Assunção", "py", "par", 3.0, "#CE1126", "#0033A0"),
  _xc("lbt", "Libertad", "Assunção", "py", "par", 2.9, "#FFFFFF", "#000000"),
  _xc("dzg", "Dinamo Zagreb", "Zagreb", "hr", "hnl", 3.6, "#0033A0", "#FFFFFF"),
  _xc("haj", "Hajduk Split", "Split", "hr", "hnl", 3.3, "#FFFFFF", "#0033A0"),
  _xc("rij", "Rijeka", "Rijeka", "hr", "hnl", 3.2, "#FFFFFF", "#0033A0"),
  _xc("oly", "Olympiacos", "Pireu", "gr", "slg", 3.6, "#CE1126", "#FFFFFF"),
  _xc("pao", "Panathinaikos", "Atenas", "gr", "slg", 3.4, "#007A33", "#FFFFFF"),
  _xc("aek", "AEK Atenas", "Atenas", "gr", "slg", 3.3, "#FFD100", "#000000"),
  _xc("zen", "Zenit", "São Petersburgo", "ru", "rpl", 3.8, "#00A0E3", "#FFFFFF"),
  _xc("spm", "Spartak Moscou", "Moscou", "ru", "rpl", 3.6, "#CE1126", "#FFFFFF"),
  _xc("csk", "CSKA Moscou", "Moscou", "ru", "rpl", 3.5, "#CE1126", "#0033A0"),
  _xc("wyd", "Wydad", "Casablanca", "ma", "bot", 2.9, "#CE1126", "#FFFFFF"),
  _xc("rca", "Raja Casablanca", "Casablanca", "ma", "bot", 2.8, "#007A33", "#FFFFFF"),
  _xc("asfr", "FAR Rabat", "Rabat", "ma", "bot", 2.6, "#CE1126", "#007A33"),
  _xc("uls", "Ulsan HD", "Ulsan", "kr", "kle", 3.3, "#0033A0", "#FFFFFF"),
  _xc("jhb", "Jeonbuk", "Jeonju", "kr", "kle", 3.2, "#007A33", "#FFD100"),
  _xc("fcs", "FC Seoul", "Seul", "kr", "kle", 3.1, "#CE1126", "#000000"),
  _xc("cvy", "Cavalry FC", "Calgary", "ca", "cpl", 2.8, "#CE1126", "#FFFFFF"),
  _xc("ato", "Atlético Ottawa", "Ottawa", "ca", "cpl", 2.7, "#CE1126", "#000000"),
  _xc("pfc", "Pacific FC", "Victoria", "ca", "cpl", 2.6, "#5C2D91", "#2EC4B6")
]);

/* League trophy / cup mapping — proper names via TROPHIES ids */
(function patchLeagueTrophies() {
  var map = {
    bra: { trophy: "brasileirao", cupTrophy: "copa_br" },
    brb: { trophy: "serie_b", cupTrophy: "copa_br" },
    arg: { trophy: "ligapro", cupTrophy: "copa_arg" },
    uru: { trophy: "uruprimera", cupTrophy: "copa_uy" },
    col: { trophy: "colbetplay", cupTrophy: "copa_col" },
    mex: { trophy: "liga_mx", cupTrophy: "copa_mx" },
    por: { trophy: "primerliga", cupTrophy: "taca_pt" },
    esp: { trophy: "laliga", cupTrophy: "copa_rey" },
    eng: { trophy: "premier", cupTrophy: "fa_cup" },
    fra: { trophy: "ligue1", cupTrophy: "coupe_fr" },
    ita: { trophy: "seriea", cupTrophy: "coppa_ita" },
    ger: { trophy: "bundesliga", cupTrophy: "dfb_pokal" },
    ned: { trophy: "eredivisie", cupTrophy: "knvb" },
    usa: { trophy: "mls", cupTrophy: "us_open" },
    jpn: { trophy: "j1", cupTrophy: "emperor" },
    nga: { trophy: "npfl", cupTrophy: "copa_ng" },
    sen: { trophy: "senliga", cupTrophy: "copa_sn" },
    bel: { trophy: "proleague", cupTrophy: "copa_be" },
    tur: { trophy: "superlig", cupTrophy: "copa_tr" },
    sco: { trophy: "scottish", cupTrophy: "scottish_cup" },
    chi: { trophy: "primera_cl", cupTrophy: "copa_cl" },
    ecu: { trophy: "liga_ec", cupTrophy: "copa_ec" },
    par: { trophy: "primera_py", cupTrophy: "copa_py" },
    /* Hrvatski kup: no free clean trophy cutout — cupTrophy false skips the generic copa fallback */
    hnl: { trophy: "hnl", cupTrophy: false },
    slg: { trophy: "slgreece", cupTrophy: "greek_cup" },
    rpl: { trophy: "rpl", cupTrophy: "russian_cup" },
    bot: { trophy: "botola", cupTrophy: "trone" },
    kle: { trophy: "kleague", cupTrophy: "korea_cup" },
    cpl: { trophy: "cpl", cupTrophy: "can_champ" },
    /* Sydbank Pokalen: no separate free cutout — the DBU cup image is the Superliga trophy. cupTrophy false skips copa.png */
    dsl: { trophy: "dsliga", cupTrophy: false },
    all: { trophy: "allsvenskan", cupTrophy: "svenska_cup" },
    eli: { trophy: "eliteserien", cupTrophy: "nm_cup" },
    /* King's Cup, Egypt Cup, Coupe d'Algérie, Coupe de Tunisie, Emir Cup, UAE President's Cup: no free clean cutout — cupTrophy false skips generic copa.png */
    spl: { trophy: "spl", cupTrophy: false },
    epl: { trophy: "epl", cupTrophy: false },
    alg: { trophy: "alg1", cupTrophy: false },
    tun: { trophy: "tun1", cupTrophy: false },
    qsl: { trophy: "qsl", cupTrophy: false },
    uae: { trophy: "uaepl", cupTrophy: false },
    brc: { trophy: "serie_c", cupTrophy: "copa_br" },
    eng2: { trophy: "championship", cupTrophy: "fa_cup" },
    ger2: { trophy: "bundesliga2", cupTrophy: "dfb_pokal" },
    fra2: { trophy: "ligue2", cupTrophy: "coupe_fr" },
    esp2: { trophy: "segunda", cupTrophy: "copa_rey" },
    ita2: { trophy: "serie_b_ita", cupTrophy: "coppa_ita" }
  };
  for (var i = 0; i < LEAGUES.length; i++) {
    var m = map[LEAGUES[i].id];
    if (!m) continue;
    LEAGUES[i].trophy = m.trophy;
    LEAGUES[i].cupTrophy = m.cupTrophy;
  }
})();

/* Lower-tier / extra clubs so thin nations always have ≥3 academy options */
CLUBS = CLUBS.concat([
  _xc("dan", "Danubio", "Montevidéu", "uy", "uru", 2.6, "#000000", "#FFFFFF"),
  _xc("rivu", "River Plate UY", "Montevidéu", "uy", "uru", 2.5, "#CE1126", "#FFFFFF"),
  _xc("jun", "Junior", "Barranquilla", "co", "col", 3.0, "#CE1126", "#FFFFFF"),
  _xc("dep", "Deportivo Cali", "Cali", "co", "col", 2.9, "#007A33", "#FFFFFF"),
  _xc("tol", "Toluca", "Toluca", "mx", "mex", 3.4, "#CE1126", "#FFFFFF"),
  _xc("paz", "Cruz Azul", "Cidade do México", "mx", "mex", 3.5, "#0033A0", "#FFFFFF"),
  _xc("sea", "Seattle Sounders", "Seattle", "us", "usa", 3.1, "#5D9732", "#0033A0"),
  _xc("nyc", "NYCFC", "Nova York", "us", "usa", 3.0, "#6CACE4", "#00285E"),
  _xc("kaw", "Kawasaki Frontale", "Kawasaki", "jp", "jpn", 3.0, "#87CEEB", "#000080"),
  _xc("cer", "Cerezo Osaka", "Osaka", "jp", "jpn", 2.8, "#CE1126", "#FF69B4"),
  _xc("rvs", "Rivers United", "Port Harcourt", "ng", "nga", 2.2, "#0033A0", "#FFFFFF"),
  _xc("ranfc", "Rangers Int'l", "Enugu", "ng", "nga", 2.1, "#FFD700", "#0033A0"),
  _xc("gen", "Génération Foot", "Dakar", "sn", "sen", 2.0, "#00853F", "#E31C23"),
  _xc("ouc", "US Ouakam", "Dakar", "sn", "sen", 1.9, "#FFFFFF", "#00853F"),
  _xc("hur", "Huracán", "Buenos Aires", "ar", "arg", 3.2, "#FFFFFF", "#CE1126"),
  _xc("vel", "Vélez", "Buenos Aires", "ar", "arg", 3.4, "#FFFFFF", "#0033A0"),
  _xc("gio", "Náutico", "Recife", "br", "brb", 2.3, "#0033A0", "#FFFFFF"),
  _xc("csa", "CSA", "Maceió", "br", "brc", 2.1, "#0033A0", "#FFFFFF"),

  /* --- synced Brasileirão 2026 (Série A promoted / missing) --- */
  _xc("mir", "Mirassol", "Mirassol", "br", "bra", 3.2, "#FFD100", "#0066B3"),
  _xc("vit", "Vitória", "Salvador", "br", "bra", 3.3, "#E31837", "#000000"),
  _xc("ctb", "Coritiba", "Curitiba", "br", "bra", 3.3, "#007A33", "#FFFFFF"),
  _xc("chp", "Chapecoense", "Chapecó", "br", "bra", 3.1, "#007A33", "#FFFFFF"),
  _xc("rem", "Remo", "Belém", "br", "bra", 3.0, "#0033A0", "#FFFFFF"),

  /* --- synced Brasileirão Série B 2026 --- */
  _xc("jve", "Juventude", "Caxias do Sul", "br", "brb", 2.9, "#007A33", "#FFFFFF"),
  _xc("lon", "Londrina", "Londrina", "br", "brb", 2.5, "#0033A0", "#FFFFFF"),
  _xc("sbe", "São Bernardo", "São Bernardo", "br", "brb", 2.5, "#FFD100", "#000000"),
  _xc("cri", "Criciúma", "Criciúma", "br", "brb", 2.7, "#FFD100", "#000000"),
  _xc("nov", "Novorizontino", "Novo Horizonte", "br", "brb", 2.6, "#FFD100", "#000000"),
  _xc("crb", "CRB", "Maceió", "br", "brb", 2.6, "#E31837", "#FFFFFF"),
  _xc("cui", "Cuiabá", "Cuiabá", "br", "brb", 2.7, "#007A33", "#FFD100"),
  _xc("ago", "Atlético-GO", "Goiânia", "br", "brb", 2.7, "#E31837", "#000000"),
  _xc("ope", "Operário-PR", "Ponta Grossa", "br", "brb", 2.5, "#000000", "#FFFFFF"),
  _xc("vna", "Vila Nova", "Goiânia", "br", "brb", 2.5, "#E31837", "#FFFFFF"),
  _xc("amg", "América-MG", "Belo Horizonte", "br", "brb", 2.8, "#007A33", "#000000"),
  _xc("athm", "Athletic-MG", "São João del-Rei", "br", "brb", 2.4, "#000000", "#FFFFFF"),
  _xc("bsp", "Botafogo-SP", "Ribeirão Preto", "br", "brb", 2.5, "#E31837", "#000000"),

  /* --- Premier League 2026/27 (promoted + missing top-flight) --- */
  _xc("cov", "Coventry", "Coventry", "en", "eng", 3.5, "#77C7F2", "#FFFFFF"),
  _xc("ips", "Ipswich", "Ipswich", "en", "eng", 3.6, "#0033A0", "#FFFFFF"),
  _xc("hul", "Hull City", "Hull", "en", "eng", 3.5, "#F5A12D", "#000000"),
  _xc("bou", "Bournemouth", "Bournemouth", "en", "eng", 3.7, "#DA291C", "#000000"),
  _xc("bre", "Brentford", "Londres", "en", "eng", 3.8, "#E30613", "#FFFFFF"),
  _xc("lee", "Leeds", "Leeds", "en", "eng", 3.8, "#FFFFFF", "#1D355E"),
  _xc("sun", "Sunderland", "Sunderland", "en", "eng", 3.6, "#E30613", "#FFFFFF"),

  /* --- Bundesliga 2026/27 promoted --- */
  _xc("s04", "Schalke", "Gelsenkirchen", "de", "ger", 3.6, "#004D95", "#FFFFFF"),
  _xc("elv", "Elversberg", "Elversberg", "de", "ger", 3.2, "#FFFFFF", "#000000"),
  _xc("pad", "Paderborn", "Paderborn", "de", "ger", 3.3, "#005CA9", "#FFFFFF"),

  /* --- Ligue 1 2026/27 promoted --- */
  _xc("tro", "Troyes", "Troyes", "fr", "fra", 3.2, "#0033A0", "#FFFFFF"),
  _xc("lem", "Le Mans", "Le Mans", "fr", "fra", 3.1, "#E30613", "#FFD100"),

  /* --- pack 1: 2026-27 top flight (Scotland, HNL, CPL, Botola) --- */
  _xc("hrt", "Hearts", "Edinburgh", "sct", "sco", 3.4, "#7A003C", "#FFFFFF"),
  _xc("hib", "Hibernian", "Edinburgh", "sct", "sco", 3.3, "#007A33", "#FFFFFF"),
  _xc("mot", "Motherwell", "Motherwell", "sct", "sco", 3.2, "#6C1D45", "#F5B335"),
  _xc("dun", "Dundee", "Dundee", "sct", "sco", 3.1, "#132257", "#FFFFFF"),
  _xc("duu", "Dundee United", "Dundee", "sct", "sco", 3.1, "#F15A22", "#000000"),
  _xc("kil", "Kilmarnock", "Kilmarnock", "sct", "sco", 3.0, "#0033A0", "#FFFFFF"),
  _xc("stm", "St Mirren", "Paisley", "sct", "sco", 3.0, "#000000", "#FFFFFF"),
  _xc("fal", "Falkirk", "Falkirk", "sct", "sco", 3.0, "#001F5B", "#FFFFFF"),
  _xc("sjo", "St Johnstone", "Perth", "sct", "sco", 2.9, "#003DA5", "#FFFFFF"),

  _xc("var", "Varaždin", "Varaždin", "hr", "hnl", 3.2, "#0033A0", "#FFFFFF"),
  _xc("osi", "Osijek", "Osijek", "hr", "hnl", 3.1, "#0057A8", "#FFFFFF"),
  _xc("lok", "Lokomotiva", "Zagreb", "hr", "hnl", 3.0, "#0033A0", "#FFFFFF"),
  _xc("ist", "Istra 1961", "Pula", "hr", "hnl", 3.0, "#007A33", "#FFE500"),
  _xc("gor", "Gorica", "Velika Gorica", "hr", "hnl", 2.9, "#0057B8", "#FFFFFF"),
  _xc("slb", "Slaven Belupo", "Koprivnica", "hr", "hnl", 2.9, "#0033A0", "#FFFFFF"),
  _xc("rud", "Rudeš", "Zagreb", "hr", "hnl", 2.8, "#003DA5", "#FFFFFF"),

  _xc("frg", "Forge FC", "Hamilton", "ca", "cpl", 2.9, "#F26522", "#111111"),
  _xc("vfc", "Vancouver FC", "Langley", "ca", "cpl", 2.6, "#212322", "#FFFFFF"),
  _xc("hfx", "HFX Wanderers", "Halifax", "ca", "cpl", 2.5, "#00205B", "#6EC1E4"),
  _xc("itr", "Inter Toronto", "Toronto", "ca", "cpl", 2.5, "#0A2342", "#C4A35A"),
  _xc("sup", "Supra du Québec", "Laval", "ca", "cpl", 2.4, "#E10600", "#002D72"),

  _xc("masf", "MAS Fez", "Fez", "ma", "bot", 3.0, "#F5D000", "#111111"),
  _xc("rsb", "RS Berkane", "Berkane", "ma", "bot", 2.8, "#F36C21", "#111111"),
  _xc("fus", "FUS Rabat", "Rabat", "ma", "bot", 2.7, "#C8102E", "#FFFFFF"),
  _xc("husa", "Hassania Agadir", "Agadir", "ma", "bot", 2.6, "#C8102E", "#FFFFFF"),
  _xc("irt", "Ittihad Tanger", "Tanger", "ma", "bot", 2.6, "#0057B8", "#FFFFFF"),
  _xc("codm", "CODM Meknès", "Meknès", "ma", "bot", 2.5, "#E10600", "#FFFFFF"),
  _xc("dhj", "Difaâ El Jadida", "El Jadida", "ma", "bot", 2.5, "#007A33", "#FFFFFF"),
  _xc("kacm", "Kawkab Marrakech", "Marrakech", "ma", "bot", 2.4, "#C8102E", "#FFFFFF"),
  _xc("uts", "Union Touarga", "Rabat", "ma", "bot", 2.4, "#F5C518", "#111111"),
  _xc("mat", "MA Tétouan", "Tétouan", "ma", "bot", 2.3, "#C8102E", "#FFFFFF"),
  _xc("rcaz", "RCA Zemamra", "Zemamra", "ma", "bot", 2.3, "#0057B8", "#FFFFFF"),
  _xc("usat", "Amal Tiznit", "Tiznit", "ma", "bot", 2.2, "#0057B8", "#FFFFFF"),
  _xc("wst", "Widad Témara", "Témara", "ma", "bot", 2.1, "#C8102E", "#0033A0"),

  /* --- pack 2: 2026-27 top flight (Belgium, Chile, Greece, Korea) --- */
  _xc("usg", "Union SG", "Bruxelas", "be", "bel", 3.8, "#FFE000", "#000055"),
  _xc("gnt", "Gent", "Gante", "be", "bel", 3.6, "#0023DD", "#FFFFFF"),
  _xc("ant", "Antwerp", "Antuérpia", "be", "bel", 3.5, "#FF0000", "#FFFFFF"),
  _xc("std", "Standard Liège", "Liège", "be", "bel", 3.5, "#DD0000", "#FFFFFF"),
  _xc("mec", "Mechelen", "Mechelen", "be", "bel", 3.4, "#FFD700", "#000000"),
  _xc("cha", "Charleroi", "Charleroi", "be", "bel", 3.4, "#000000", "#FFFFFF"),
  _xc("ceb", "Cercle Brugge", "Bruges", "be", "bel", 3.3, "#00852D", "#000000"),
  _xc("stvv", "Sint-Truiden", "Sint-Truiden", "be", "bel", 3.3, "#FFFF00", "#0000FF"),
  _xc("wes", "Westerlo", "Westerlo", "be", "bel", 3.3, "#FFFF00", "#0000FF"),
  _xc("ohl", "OH Leuven", "Lovaina", "be", "bel", 3.2, "#E10600", "#007A33"),
  _xc("zwa", "Zulte Waregem", "Waregem", "be", "bel", 3.2, "#FF0026", "#009640"),
  _xc("louv", "La Louvière", "La Louvière", "be", "bel", 3.1, "#009150", "#FFFFFF"),
  _xc("kor", "Kortrijk", "Kortrijk", "be", "bel", 3.0, "#FF0000", "#FFFFFF"),
  _xc("lom", "Lommel", "Lommel", "be", "bel", 2.9, "#009150", "#FFFFFF"),
  _xc("bev", "Beveren", "Beveren", "be", "bel", 2.9, "#F5C518", "#0033A0"),

  _xc("coq", "Coquimbo Unido", "Coquimbo", "cl", "chi", 3.4, "#FFDE00", "#000000"),
  _xc("evcl", "Everton Viña", "Viña del Mar", "cl", "chi", 3.3, "#003159", "#FFD100"),
  _xc("plst", "Palestino", "Santiago", "cl", "chi", 3.3, "#007A33", "#FFFFFF"),
  _xc("hua", "Huachipato", "Talcahuano", "cl", "chi", 3.2, "#0000FF", "#000000"),
  _xc("aud", "Audax Italiano", "Santiago", "cl", "chi", 3.2, "#1C9E1C", "#FFFFFF"),
  _xc("nub", "Ñublense", "Chillán", "cl", "chi", 3.2, "#FF0000", "#FFFFFF"),
  _xc("lim", "Deportes Limache", "Limache", "cl", "chi", 3.1, "#D5303E", "#000000"),
  _xc("dls", "La Serena", "La Serena", "cl", "chi", 3.1, "#B20837", "#FFFFFF"),
  _xc("ohig", "O'Higgins", "Rancagua", "cl", "chi", 3.1, "#83CCF9", "#FFFFFF"),
  _xc("cob", "Cobresal", "El Salvador", "cl", "chi", 3.0, "#F36C21", "#000000"),
  _xc("ulc", "Unión La Calera", "La Calera", "cl", "chi", 3.0, "#EE0000", "#FFFFFF"),
  _xc("udec", "Universidad de Concepción", "Concepción", "cl", "chi", 2.9, "#FFFF00", "#010633"),
  _xc("dcon", "Deportes Concepción", "Concepción", "cl", "chi", 2.8, "#5C4AB0", "#FFFFFF"),

  _xc("paok", "PAOK", "Tessalônica", "gr", "slg", 3.5, "#000000", "#FFFFFF"),
  _xc("ari", "Aris", "Tessalônica", "gr", "slg", 3.3, "#FFD100", "#000000"),
  _xc("ofi", "OFI", "Heraclião", "gr", "slg", 3.2, "#000000", "#FFFFFF"),
  _xc("atro", "Atromitos", "Atenas", "gr", "slg", 3.1, "#0033A0", "#FFFFFF"),
  _xc("ast", "Asteras Tripolis", "Trípoli", "gr", "slg", 3.1, "#FFD100", "#0033A0"),
  _xc("vol", "Volos", "Volos", "gr", "slg", 3.0, "#FF0000", "#0033A0"),
  _xc("kif", "Kifisia", "Kifisia", "gr", "slg", 3.0, "#002147", "#FFFFFF"),
  _xc("lvk", "Levadiakos", "Livadeia", "gr", "slg", 3.0, "#005754", "#FFFFFF"),
  _xc("pnt", "Panetolikos", "Agrinio", "gr", "slg", 2.9, "#FFEA00", "#0033A0"),
  _xc("irk", "Iraklis", "Tessalônica", "gr", "slg", 2.8, "#000066", "#FFFFFF"),
  _xc("kal", "Kalamata", "Kalamata", "gr", "slg", 2.7, "#000000", "#FFFFFF"),

  _xc("poh", "Pohang Steelers", "Pohang", "kr", "kle", 3.3, "#C8102E", "#000000"),
  _xc("jsk", "Jeju SK", "Seogwipo", "kr", "kle", 3.1, "#EC6B32", "#FFFFFF"),
  _xc("gwn", "Gangwon FC", "Chuncheon", "kr", "kle", 3.1, "#F53A45", "#000000"),
  _xc("dhc", "Daejeon Hana", "Daejeon", "kr", "kle", 3.0, "#007854", "#FFFFFF"),
  _xc("icu", "Incheon United", "Incheon", "kr", "kle", 3.0, "#0000FF", "#000000"),
  _xc("any", "FC Anyang", "Anyang", "kr", "kle", 2.9, "#4B1D80", "#171715"),
  _xc("gmc", "Gimcheon Sangmu", "Gimcheon", "kr", "kle", 2.8, "#FF0000", "#000000"),
  _xc("buc", "Bucheon FC", "Bucheon", "kr", "kle", 2.7, "#FF0000", "#000000"),
  _xc("gwj", "Gwangju FC", "Gwangju", "kr", "kle", 2.6, "#EDBA23", "#641C20"),

  _xc("trb", "Trabzonspor", "Trabzon", "tr", "tur", 3.7, "#6B1230", "#7EC8E3"),
  _xc("ibb", "Başakşehir", "Istambul", "tr", "tur", 3.5, "#0A2F6B", "#F26522"),
  _xc("sms", "Samsunspor", "Samsun", "tr", "tur", 3.4, "#E10600", "#FFFFFF"),
  _xc("goz", "Göztepe", "Esmirna", "tr", "tur", 3.4, "#FFD100", "#E10600"),
  _xc("kny", "Konyaspor", "Cônia", "tr", "tur", 3.3, "#007A33", "#FFFFFF"),
  _xc("ksp", "Kasımpaşa", "Istambul", "tr", "tur", 3.3, "#0033A0", "#FFFFFF"),
  _xc("aly", "Alanyaspor", "Alanya", "tr", "tur", 3.3, "#F36C21", "#007A33"),
  _xc("riz", "Rizespor", "Rize", "tr", "tur", 3.2, "#0033A0", "#E10600"),
  _xc("gfk", "Gaziantep", "Gaziantep", "tr", "tur", 3.2, "#E10600", "#000000"),
  _xc("kcl", "Kocaelispor", "İzmit", "tr", "tur", 3.2, "#006B3F", "#000000"),
  _xc("gnb", "Gençlerbirliği", "Ancara", "tr", "tur", 3.1, "#000000", "#C8102E"),
  _xc("eyu", "Eyüpspor", "Istambul", "tr", "tur", 3.1, "#5C2D91", "#FFD100"),
  _xc("amd", "Amedspor", "Diyarbakır", "tr", "tur", 3.0, "#007A33", "#E10600"),
  _xc("erz", "Erzurumspor", "Erzurum", "tr", "tur", 2.9, "#0096D6", "#FFFFFF"),
  _xc("crm", "Çorum", "Çorum", "tr", "tur", 2.8, "#E10600", "#000000"),

  _xc("idv", "Independiente del Valle", "Sangolquí", "ec", "ecu", 3.2, "#000000", "#FFFFFF"),
  _xc("ucq", "Universidad Católica", "Quito", "ec", "ecu", 3.0, "#5BC2E7", "#000000"),
  _xc("auc", "Aucas", "Quito", "ec", "ecu", 2.9, "#FFD100", "#E10600"),
  _xc("dcu", "Deportivo Cuenca", "Cuenca", "ec", "ecu", 2.9, "#007A33", "#E10600"),
  _xc("dlf", "Delfín", "Manta", "ec", "ecu", 2.8, "#0033A0", "#FFD100"),
  _xc("ors", "Orense", "Machala", "ec", "ecu", 2.8, "#006B3F", "#C4A35A"),
  _xc("mca", "Macará", "Ambato", "ec", "ecu", 2.7, "#0033A0", "#FFFFFF"),
  _xc("mur", "Mushuc Runa", "Ambato", "ec", "ecu", 2.7, "#007A33", "#E10600"),
  _xc("tec", "Técnico Universitario", "Ambato", "ec", "ecu", 2.7, "#E10600", "#FFFFFF"),
  _xc("mfc", "Manta FC", "Manta", "ec", "ecu", 2.6, "#E10600", "#0033A0"),
  _xc("lfc", "Libertad FC", "Loja", "ec", "ecu", 2.6, "#000000", "#C4A35A"),
  _xc("gyc", "Guayaquil City", "Guayaquil", "ec", "ecu", 2.5, "#0033A0", "#87CEEB"),
  _xc("leo", "Leones", "Atuntaqui", "ec", "ecu", 2.4, "#E10600", "#000000"),

  _xc("gni", "Guaraní", "Assunção", "py", "par", 3.0, "#FFD100", "#000000"),
  _xc("npy", "Nacional", "Assunção", "py", "par", 2.9, "#E10600", "#0033A0"),
  _xc("slu", "Sportivo Luqueño", "Luque", "py", "par", 2.8, "#0033A0", "#FFD100"),
  _xc("tri", "Sportivo Trinidense", "Assunção", "py", "par", 2.7, "#0033A0", "#FFD100"),
  _xc("aml", "Sportivo Ameliano", "Assunção", "py", "par", 2.7, "#0033A0", "#FFFFFF"),
  _xc("dmy", "2 de Mayo", "Pedro Juan Caballero", "py", "par", 2.6, "#0033A0", "#FFFFFF"),
  _xc("rec", "Recoleta", "Assunção", "py", "par", 2.6, "#000000", "#C4A35A"),
  _xc("rnu", "Rubio Ñu", "Assunção", "py", "par", 2.5, "#007A33", "#FFFFFF"),
  _xc("slz", "San Lorenzo", "San Lorenzo", "py", "par", 2.4, "#E10600", "#FFFFFF"),

  _xc("krd", "Krasnodar", "Krasnodar", "ru", "rpl", 3.7, "#007A33", "#000000"),
  _xc("lmo", "Lokomotiv", "Moscou", "ru", "rpl", 3.6, "#E10600", "#007A33"),
  _xc("dmo", "Dínamo Moscou", "Moscou", "ru", "rpl", 3.6, "#0033A0", "#FFFFFF"),
  _xc("rub", "Rubin Kazan", "Kazan", "ru", "rpl", 3.4, "#8B1E3F", "#FFFFFF"),
  _xc("ros", "Rostov", "Rostov do Don", "ru", "rpl", 3.3, "#FFD100", "#0033A0"),
  _xc("kry", "Krylia Sovetov", "Samara", "ru", "rpl", 3.3, "#0033A0", "#FFFFFF"),
  _xc("akh", "Akhmat", "Grózni", "ru", "rpl", 3.2, "#007A33", "#FFFFFF"),
  _xc("bal", "Baltika", "Kaliningrado", "ru", "rpl", 3.2, "#0033A0", "#FFFFFF"),
  _xc("orb", "Orenburg", "Orenburgo", "ru", "rpl", 3.1, "#00205B", "#FFFFFF"),
  _xc("dmk", "Dínamo Makhatchkala", "Makhatchkala", "ru", "rpl", 3.1, "#0033A0", "#FFFFFF"),
  _xc("akr", "Akron", "Togliatti", "ru", "rpl", 3.0, "#E10600", "#000000"),
  _xc("rod", "Rodina", "Moscou", "ru", "rpl", 2.9, "#001B3A", "#00AEEF"),
  _xc("fak", "Fakel", "Voronej", "ru", "rpl", 2.8, "#0033A0", "#E10600")
]);

/* --- pack nórdico: Superliga 2026-27, Allsvenskan 2026, Eliteserien 2026 --- */
CLUBS = CLUBS.concat([
  _xc("agf", "AGF", "Aarhus", "dk", "dsl", 3.4, "#FFFFFF", "#0033A0"),
  _xc("bfc", "Brøndby", "Brøndby", "dk", "dsl", 3.6, "#FFD100", "#0057B8"),
  _xc("fck", "FC Copenhagen", "Copenhague", "dk", "dsl", 3.9, "#FFFFFF", "#003DA5"),
  _xc("ach", "AC Horsens", "Horsens", "dk", "dsl", 3.0, "#FFD100", "#111111"),
  _xc("lyb", "Lyngby", "Lyngby", "dk", "dsl", 3.0, "#0033A0", "#FFFFFF"),
  _xc("fcm", "Midtjylland", "Herning", "dk", "dsl", 3.8, "#111111", "#C8102E"),
  _xc("fcn", "Nordsjælland", "Farum", "dk", "dsl", 3.5, "#E10600", "#FFD100"),
  _xc("obo", "OB", "Odense", "dk", "dsl", 3.1, "#0057B8", "#FFFFFF"),
  _xc("rfc", "Randers", "Randers", "dk", "dsl", 3.2, "#111111", "#FFFFFF"),
  _xc("sif", "Silkeborg", "Silkeborg", "dk", "dsl", 3.2, "#00AEEF", "#FFFFFF"),
  _xc("son", "Sønderjyske", "Haderslev", "dk", "dsl", 3.1, "#00205B", "#FFFFFF"),
  _xc("vff", "Viborg", "Viborg", "dk", "dsl", 3.3, "#007A53", "#FFFFFF"),

  _xc("aik", "AIK", "Solna", "se", "all", 3.5, "#FFD100", "#00205B"),
  _xc("bkh", "Häcken", "Gotemburgo", "se", "all", 3.4, "#FFD100", "#111111"),
  _xc("deg", "Degerfors", "Degerfors", "se", "all", 2.9, "#E10600", "#FFFFFF"),
  _xc("dif", "Djurgården", "Estocolmo", "se", "all", 3.6, "#FFD100", "#0057B8"),
  _xc("gais", "GAIS", "Gotemburgo", "se", "all", 3.1, "#007A33", "#E10600"),
  _xc("hbk", "Halmstad", "Halmstad", "se", "all", 2.9, "#0057B8", "#FFD100"),
  _xc("ham", "Hammarby", "Estocolmo", "se", "all", 3.6, "#007A33", "#FFFFFF"),
  _xc("bp", "Brommapojkarna", "Estocolmo", "se", "all", 3.0, "#111111", "#C8102E"),
  _xc("elf", "Elfsborg", "Borås", "se", "all", 3.4, "#FFD100", "#111111"),
  _xc("ifkg", "IFK Göteborg", "Gotemburgo", "se", "all", 3.3, "#0057B8", "#FFFFFF"),
  _xc("sir", "Sirius", "Uppsala", "se", "all", 3.3, "#111111", "#0057B8"),
  _xc("kff", "Kalmar", "Kalmar", "se", "all", 3.0, "#E10600", "#FFFFFF"),
  _xc("mff", "Malmö", "Malmö", "se", "all", 3.8, "#5BC2E7", "#FFFFFF"),
  _xc("mja", "Mjällby", "Hällevik", "se", "all", 3.2, "#FFD100", "#111111"),
  _xc("vsk", "Västerås", "Västerås", "se", "all", 3.0, "#007A33", "#FFFFFF"),
  _xc("ois", "Örgryte", "Gotemburgo", "se", "all", 2.8, "#E10600", "#0033A0"),

  _xc("aafk", "Aalesund", "Ålesund", "no", "eli", 2.8, "#F36C21", "#0033A0"),
  _xc("bog", "Bodø/Glimt", "Bodø", "no", "eli", 3.9, "#FFD100", "#111111"),
  _xc("brnn", "Brann", "Bergen", "no", "eli", 3.5, "#E10600", "#FFFFFF"),
  _xc("ffk", "Fredrikstad", "Fredrikstad", "no", "eli", 3.1, "#E10600", "#FFFFFF"),
  _xc("hkam", "HamKam", "Hamar", "no", "eli", 3.0, "#007A33", "#FFFFFF"),
  _xc("kfum", "KFUM", "Oslo", "no", "eli", 2.9, "#E10600", "#0033A0"),
  _xc("kbk", "Kristiansund", "Kristiansund", "no", "eli", 2.9, "#0033A0", "#FFFFFF"),
  _xc("lsk", "Lillestrøm", "Lillestrøm", "no", "eli", 3.3, "#FFD100", "#111111"),
  _xc("mol", "Molde", "Molde", "no", "eli", 3.6, "#0057B8", "#FFFFFF"),
  _xc("rbk", "Rosenborg", "Trondheim", "no", "eli", 3.6, "#FFFFFF", "#111111"),
  _xc("sand", "Sandefjord", "Sandefjord", "no", "eli", 2.9, "#0033A0", "#E10600"),
  _xc("s08", "Sarpsborg 08", "Sarpsborg", "no", "eli", 3.1, "#0033A0", "#FFFFFF"),
  _xc("ikst", "Start", "Kristiansand", "no", "eli", 2.8, "#FFD100", "#0033A0"),
  _xc("til", "Tromsø", "Tromsø", "no", "eli", 3.3, "#E10600", "#FFFFFF"),
  _xc("vifk", "Viking", "Stavanger", "no", "eli", 3.6, "#6C1D2C", "#FFD100"),
  _xc("vif", "Vålerenga", "Oslo", "no", "eli", 3.2, "#0033A0", "#E10600")
]);

/* --- países árabes: SPL / EPL / Ligue 1 ALG / Ligue 1 TUN / QSL / UAE 2026-27 --- */
CLUBS = CLUBS.concat([
  _xc("abha", "Abha", "Abha", "sa", "spl", 2.7, "#1B4F9C", "#FFFFFF"),
  _xc("ahli", "Al-Ahli", "Jidá", "sa", "spl", 4.0, "#006C35", "#FFFFFF"),
  _xc("diri", "Al-Diriyah", "Diriyah", "sa", "spl", 3.0, "#C4A35A", "#111111"),
  _xc("etti", "Al-Ettifaq", "Dammam", "sa", "spl", 3.4, "#007A33", "#FFFFFF"),
  _xc("fais", "Al-Faisaly", "Harmah", "sa", "spl", 2.8, "#F36C21", "#0033A0"),
  _xc("fath", "Al-Fateh", "Al-Mubarraz", "sa", "spl", 3.1, "#007A33", "#0033A0"),
  _xc("fayh", "Al-Fayha", "Majmaah", "sa", "spl", 3.1, "#F26522", "#111111"),
  _xc("hazm", "Al-Hazem", "Ar Rass", "sa", "spl", 2.9, "#F5B400", "#111111"),
  _xc("hil", "Al-Hilal", "Riade", "sa", "spl", 4.2, "#0033A0", "#FFFFFF"),
  _xc("ittj", "Al-Ittihad", "Jidá", "sa", "spl", 4.0, "#FFD100", "#111111"),
  _xc("khlj", "Al-Khaleej", "Saihat", "sa", "spl", 2.9, "#007A33", "#FFD100"),
  _xc("khol", "Al-Kholood", "Ar Rass", "sa", "spl", 3.2, "#5C2D91", "#FFFFFF"),
  _xc("nass", "Al-Nassr", "Riade", "sa", "spl", 4.1, "#FFD100", "#0033A0"),
  _xc("qads", "Al-Qadsiah", "Khobar", "sa", "spl", 3.7, "#C8102E", "#FFD100"),
  _xc("riyd", "Al-Riyadh", "Riade", "sa", "spl", 3.0, "#111111", "#E10600"),
  _xc("shab", "Al-Shabab", "Riade", "sa", "spl", 3.5, "#FFFFFF", "#111111"),
  _xc("taaw", "Al-Taawoun", "Buraidah", "sa", "spl", 3.3, "#FFD100", "#0033A0"),
  _xc("neom", "NEOM", "Tabuk", "sa", "spl", 3.6, "#111111", "#00B5B8"),
  _xc("abq", "Abou Qir", "Alexandria", "eg", "epl", 2.6, "#007A33", "#FFD100"),
  _xc("ahly", "Al Ahly", "Cairo", "eg", "epl", 4.0, "#C8102E", "#FFFFFF"),
  _xc("mokw", "Mokawloon", "Cairo", "eg", "epl", 3.0, "#FFD100", "#111111"),
  _xc("asyt", "Asyut Petroleum", "Asyut", "eg", "epl", 2.6, "#FFD100", "#111111"),
  _xc("ceram", "Ceramica Cleopatra", "Cairo", "eg", "epl", 3.0, "#C8102E", "#FFFFFF"),
  _xc("enppi", "ENPPI", "Cairo", "eg", "epl", 3.0, "#0033A0", "#FFD100"),
  _xc("mahl", "Ghazl El Mahalla", "El Mahalla", "eg", "epl", 2.7, "#007A33", "#FFFFFF"),
  _xc("goun", "El Gouna", "El Gouna", "eg", "epl", 2.8, "#F36C21", "#007A33"),
  _xc("qana", "El Qanah", "Ismailia", "eg", "epl", 2.7, "#0033A0", "#FFFFFF"),
  _xc("itax", "Al Ittihad", "Alexandria", "eg", "epl", 3.1, "#007A33", "#C8102E"),
  _xc("masry", "Al Masry", "Port Said", "eg", "epl", 3.3, "#007A33", "#FFFFFF"),
  _xc("modn", "Modern Sport", "Cairo", "eg", "epl", 2.9, "#007A33", "#FFFFFF"),
  _xc("nbe", "National Bank", "Cairo", "eg", "epl", 2.9, "#006C35", "#C4A35A"),
  _xc("petj", "Petrojet", "Suez", "eg", "epl", 2.8, "#FFD100", "#0033A0"),
  _xc("pyr", "Pyramids", "Cairo", "eg", "epl", 3.7, "#1A1A40", "#C4A35A"),
  _xc("smou", "Smouha", "Alexandria", "eg", "epl", 3.2, "#0033A0", "#FFFFFF"),
  _xc("gaish", "El Gaish", "Cairo", "eg", "epl", 2.8, "#C8102E", "#111111"),
  _xc("wadi", "Wadi Degla", "Cairo", "eg", "epl", 2.8, "#007A33", "#FFFFFF"),
  _xc("zam", "Zamalek", "Cairo", "eg", "epl", 3.8, "#FFFFFF", "#C8102E"),
  _xc("zed", "ZED", "Cairo", "eg", "epl", 2.9, "#007A33", "#111111"),
  _xc("asoc", "ASO Chlef", "Chlef", "dz", "alg", 3.0, "#C8102E", "#FFFFFF"),
  _xc("crbel", "CR Belouizdad", "Argel", "dz", "alg", 3.4, "#FFFFFF", "#0033A0"),
  _xc("crte", "CR Témouchent", "Aïn Témouchent", "dz", "alg", 2.7, "#C8102E", "#FFFFFF"),
  _xc("csc", "CS Constantine", "Constantina", "dz", "alg", 3.1, "#007A33", "#FFFFFF"),
  _xc("esba", "ES Ben Aknoun", "Argel", "dz", "alg", 2.8, "#0033A0", "#FFFFFF"),
  _xc("esset", "ES Sétif", "Sétif", "dz", "alg", 3.3, "#111111", "#FFFFFF"),
  _xc("jseb", "JS El Biar", "El Biar", "dz", "alg", 2.6, "#0033A0", "#FFFFFF"),
  _xc("jskab", "JS Kabylie", "Tizi Ouzou", "dz", "alg", 3.4, "#FFD100", "#007A33"),
  _xc("jss", "JS Saoura", "Béchar", "dz", "alg", 2.9, "#FFD100", "#007A33"),
  _xc("mbr", "MB Rouissat", "Rouissat", "dz", "alg", 2.7, "#0033A0", "#5BC2E7"),
  _xc("mcal", "MC Alger", "Argel", "dz", "alg", 3.4, "#C8102E", "#007A33"),
  _xc("mco", "MC Oran", "Orã", "dz", "alg", 3.2, "#FFFFFF", "#C8102E"),
  _xc("oakb", "Olympique Akbou", "Akbou", "dz", "alg", 2.9, "#007A33", "#FFFFFF"),
  _xc("usbk", "US Biskra", "Biskra", "dz", "alg", 2.6, "#FFD100", "#007A33"),
  _xc("usma", "USM Alger", "Argel", "dz", "alg", 3.5, "#C8102E", "#111111"),
  _xc("usmk", "USM Khenchela", "Khenchela", "dz", "alg", 2.8, "#0033A0", "#FFFFFF"),
  _xc("asmr", "AS Marsa", "Tunes", "tn", "tun", 2.7, "#0033A0", "#FFFFFF"),
  _xc("cafr", "Club Africain", "Tunes", "tn", "tun", 3.4, "#C8102E", "#FFFFFF"),
  _xc("cabz", "CA Bizertin", "Bizerte", "tn", "tun", 3.0, "#0033A0", "#FFFFFF"),
  _xc("cshl", "CS Hammam-Lif", "Hammam-Lif", "tn", "tun", 2.8, "#007A33", "#FFFFFF"),
  _xc("cssx", "CS Sfaxien", "Sfax", "tn", "tun", 3.2, "#111111", "#FFFFFF"),
  _xc("eshs", "ES Hammam Sousse", "Hammam Sousse", "tn", "tun", 2.6, "#C8102E", "#FFFFFF"),
  _xc("esme", "ES Métlaoui", "Métlaoui", "tn", "tun", 2.6, "#FFD100", "#007A33"),
  _xc("etsa", "Étoile du Sahel", "Sousse", "tn", "tun", 3.4, "#C8102E", "#FFFFFF"),
  _xc("esper", "Espérance", "Tunes", "tn", "tun", 3.6, "#FFD100", "#C8102E"),
  _xc("esz", "ES Zarzis", "Zarzis", "tn", "tun", 2.6, "#C8102E", "#FFFFFF"),
  _xc("jseo", "JS El Omrane", "Tunes", "tn", "tun", 2.6, "#0033A0", "#FFFFFF"),
  _xc("obja", "Olympique Béja", "Béja", "tn", "tun", 2.7, "#C8102E", "#FFFFFF"),
  _xc("pss", "PS Sakiet Eddaïer", "Sfax", "tn", "tun", 2.7, "#0033A0", "#FFFFFF"),
  _xc("sttn", "Stade Tunisien", "Tunes", "tn", "tun", 2.9, "#007A33", "#FFFFFF"),
  _xc("usbg", "US Ben Guerdane", "Ben Guerdane", "tn", "tun", 2.9, "#FFD100", "#C8102E"),
  _xc("usmo", "US Monastir", "Monastir", "tn", "tun", 3.1, "#0033A0", "#FFFFFF"),
  _xc("ahld", "Al-Ahli", "Doha", "qa", "qsl", 3.0, "#007A33", "#FFFFFF"),
  _xc("arab", "Al-Arabi", "Doha", "qa", "qsl", 3.2, "#C8102E", "#FFFFFF"),
  _xc("duha", "Al-Duhail", "Doha", "qa", "qsl", 3.5, "#C8102E", "#FFFFFF"),
  _xc("ghara", "Al-Gharafa", "Al Rayyan", "qa", "qsl", 3.2, "#C8102E", "#FFFFFF"),
  _xc("rayy", "Al-Rayyan", "Al Rayyan", "qa", "qsl", 3.4, "#C8102E", "#FFD100"),
  _xc("sadd", "Al-Sadd", "Doha", "qa", "qsl", 3.6, "#FFFFFF", "#111111"),
  _xc("sail", "Al-Sailiya", "Doha", "qa", "qsl", 2.8, "#FFD100", "#111111"),
  _xc("shah", "Al-Shahaniya", "Al Shahaniya", "qa", "qsl", 2.8, "#FFD100", "#C8102E"),
  _xc("shml", "Al-Shamal", "Al Shamal", "qa", "qsl", 2.9, "#C8102E", "#FFFFFF"),
  _xc("wakr", "Al-Wakrah", "Al Wakrah", "qa", "qsl", 3.1, "#0033A0", "#FFFFFF"),
  _xc("lusa", "Lusail", "Lusail", "qa", "qsl", 2.7, "#0033A0", "#FFFFFF"),
  _xc("qsc", "Qatar SC", "Doha", "qa", "qsl", 3.0, "#FFD100", "#111111"),
  _xc("ajm", "Ajman", "Ajman", "ae", "uae", 2.9, "#F36C21", "#111111"),
  _xc("ain", "Al-Ain", "Al Ain", "ae", "uae", 3.5, "#5C2D91", "#C4A35A"),
  _xc("dhaf", "Al-Dhafra", "Madinat Zayed", "ae", "uae", 2.7, "#0033A0", "#FFFFFF"),
  _xc("jaz", "Al-Jazira", "Abu Dhabi", "ae", "uae", 3.3, "#FFFFFF", "#1B4F9C"),
  _xc("nasd", "Al-Nasr", "Dubai", "ae", "uae", 3.1, "#0033A0", "#FFD100"),
  _xc("wahd", "Al-Wahda", "Abu Dhabi", "ae", "uae", 3.2, "#6B1E2F", "#C4A35A"),
  _xc("wasl", "Al-Wasl", "Dubai", "ae", "uae", 3.2, "#FFD100", "#111111"),
  _xc("bani", "Baniyas", "Abu Dhabi", "ae", "uae", 3.0, "#0033A0", "#FFFFFF"),
  _xc("hatt", "Hatta", "Hatta", "ae", "uae", 2.6, "#C8102E", "#FFFFFF"),
  _xc("kalb", "Kalba", "Kalba", "ae", "uae", 2.9, "#FFD100", "#C8102E"),
  _xc("khor", "Khor Fakkan", "Khor Fakkan", "ae", "uae", 2.8, "#F36C21", "#FFFFFF"),
  _xc("shad", "Shabab Al-Ahli", "Dubai", "ae", "uae", 3.4, "#C8102E", "#FFFFFF"),
  _xc("sharj", "Sharjah", "Sharjah", "ae", "uae", 3.3, "#C8102E", "#FFFFFF"),
  _xc("untd", "United", "Dubai", "ae", "uae", 2.8, "#111111", "#FFFFFF"),
]);
