/* Playable nations added after world.js. Belgium/Turkey/Scotland were clubOnly. */
NATIONS = NATIONS.concat([
  { id: "sct", name: "Escócia", adj: "Escocês", conf: "uefa", ntCut: -4, flag: "img/flags/sct.png" },
  { id: "be", name: "Bélgica", adj: "Belga", conf: "uefa", ntCut: -3, flag: "img/flags/be.png" },
  { id: "tr", name: "Turquia", adj: "Turco", conf: "uefa", ntCut: -4, flag: "img/flags/tr.png" },
  { id: "cl", name: "Chile", adj: "Chileno", conf: "conmebol", ntCut: -3, flag: "img/flags/cl.png" },
  { id: "ec", name: "Equador", adj: "Equatoriano", conf: "conmebol", ntCut: -5, flag: "img/flags/ec.png" },
  { id: "py", name: "Paraguai", adj: "Paraguaio", conf: "conmebol", ntCut: -5, flag: "img/flags/py.png" },
  { id: "hr", name: "Croácia", adj: "Croata", conf: "uefa", ntCut: -1, flag: "img/flags/hr.png" },
  { id: "gr", name: "Grécia", adj: "Grego", conf: "uefa", ntCut: -4, flag: "img/flags/gr.png" },
  { id: "ru", name: "Rússia", adj: "Russo", conf: "uefa", ntCut: -3, flag: "img/flags/ru.png" },
  { id: "ma", name: "Marrocos", adj: "Marroquino", conf: "caf", ntCut: -4, flag: "img/flags/ma.png" },
  { id: "kr", name: "Coreia do Sul", adj: "Sul-coreano", conf: "afc", ntCut: -5, flag: "img/flags/kr.png" },
  { id: "ca", name: "Canadá", adj: "Canadense", conf: "concacaf", ntCut: -6, flag: "img/flags/ca.png" }
]);

/* LEAGUE_SEASON placements: Brasileirão 2026 + EUR 2026/27 — see LEAGUE_SEASON in world.js */
LEAGUES = LEAGUES.concat([
  { id: "bel", name: "Pro League", nation: "be", tier: 1, level: 3.6, continental: "ucl", size: 18, trophy: "proleague", logo: "img/leagues/bel.png", color: "#FFD700" },
  { id: "tur", name: "Süper Lig", nation: "tr", tier: 1, level: 3.7, continental: "ucl", size: 19, trophy: "superlig", logo: "img/leagues/tur.png", color: "#E30A17" },
  { id: "sco", name: "Premiership", nation: "sct", tier: 1, level: 3.3, continental: "ucl", size: 12, trophy: "scottish", logo: "img/leagues/sco.png", color: "#005EB8" },
  { id: "chi", name: "Campeonato Nacional", nation: "cl", tier: 1, level: 3.2, continental: "lib", size: 16, trophy: "primera_cl", logo: "img/leagues/chi.png", color: "#0039A6" },
  { id: "ecu", name: "LigaPro Serie A", nation: "ec", tier: 1, level: 2.9, continental: "lib", size: 16, trophy: "liga_ec", logo: "img/leagues/ecu.png", color: "#FFD100" },
  { id: "par", name: "Primera División", nation: "py", tier: 1, level: 2.8, continental: "lib", size: 12, trophy: "primera_py", logo: "img/leagues/par.png", color: "#D52B1E" },
  { id: "hnl", name: "HNL", nation: "hr", tier: 1, level: 3.3, continental: "ucl", size: 10, trophy: "hnl", logo: "img/leagues/hnl.png", color: "#FF0000" },
  { id: "slg", name: "Super League Greece", nation: "gr", tier: 1, level: 3.2, continental: "ucl", size: 14, trophy: "slgreece", logo: "img/leagues/slg.png", color: "#0D5EAF" },
  { id: "rpl", name: "Russian Premier League", nation: "ru", tier: 1, level: 3.5, continental: "ucl", size: 16, trophy: "rpl", logo: "img/leagues/rpl.png", color: "#E4181C" },
  { id: "bot", name: "Botola Pro", nation: "ma", tier: 1, level: 2.6, continental: "caf", size: 16, trophy: "botola", logo: "img/leagues/bot.png", color: "#C1272D" },
  { id: "kle", name: "K League 1", nation: "kr", tier: 1, level: 3.1, continental: "acl", size: 12, trophy: "kleague", logo: "img/leagues/kle.png", color: "#E8342A" },
  { id: "cpl", name: "Canadian Premier League", nation: "ca", tier: 1, level: 2.7, continental: "concacaf", size: 8, trophy: "cpl", logo: "img/leagues/cpl.png", color: "#E4002B" }
]);

function _xc(id, name, city, nation, leagueId, level, c1, c2) {
  return {
    id: id, name: name, city: city, nation: nation, leagueId: leagueId, level: level,
    colors: [c1, c2, c1], pattern: "solid", charge: "star", youth: true,
    crest: "img/clubs/" + id + ".png"
  };
}

CLUBS = CLUBS.concat([
  _xc("avl", "Aston Villa", "Birmingham", "en", "eng", 4.2, "#670E36", "#94BEE5"),
  _xc("whu", "West Ham", "Londres", "en", "eng2", 3.4, "#7A263A", "#1BB1E7"),
  _xc("bha", "Brighton", "Brighton", "en", "eng", 4.0, "#0057B8", "#FFFFFF"),
  _xc("eve", "Everton", "Liverpool", "en", "eng", 3.8, "#003399", "#FFFFFF"),
  _xc("cry", "Crystal Palace", "Londres", "en", "eng", 3.8, "#1B458F", "#C4122E"),
  _xc("ful", "Fulham", "Londres", "en", "eng", 3.8, "#000000", "#FFFFFF"),
  _xc("wol", "Wolves", "Wolverhampton", "en", "eng2", 3.3, "#FDB913", "#111111"),
  _xc("nfo", "Nottingham Forest", "Nottingham", "en", "eng", 3.9, "#DD0000", "#FFFFFF"),
  _xc("ath", "Athletic Bilbao", "Bilbao", "es", "esp", 4.1, "#EE2523", "#FFFFFF"),
  _xc("val", "Valencia", "Valência", "es", "esp2", 3.4, "#EEEEEE", "#D50032"),
  _xc("bet", "Betis", "Sevilha", "es", "esp", 3.9, "#00954C", "#FFFFFF"),
  _xc("celv", "Celta", "Vigo", "es", "esp2", 3.2, "#8AC3E8", "#FFFFFF"),
  _xc("ata", "Atalanta", "Bérgamo", "it", "ita", 4.2, "#1E71B8", "#000000"),
  _xc("fio", "Fiorentina", "Florença", "it", "ita", 4.0, "#482E92", "#FFFFFF"),
  _xc("bol", "Bologna", "Bolonha", "it", "ita2", 3.3, "#A20A28", "#1A1A6C"),
  _xc("tor", "Torino", "Turim", "it", "ita2", 3.2, "#8B1A1A", "#FFFFFF"),
  _xc("espy", "Espanyol", "Barcelona", "es", "esp2", 3.3, "#1E5AA8", "#FFFFFF"),
  _xc("elc", "Elche", "Elche", "es", "esp2", 3.0, "#FFFFFF", "#007A33"),
  _xc("levt", "Levante", "Valência", "es", "esp2", 3.1, "#B5003C", "#0057A8"),
  _xc("vll", "Valladolid", "Valladolid", "es", "esp2", 3.0, "#6C1D45", "#FFFFFF"),
  _xc("plrm", "Palermo", "Palermo", "it", "ita2", 3.1, "#FFD100", "#E30613"),
  _xc("bari", "Bari", "Bari", "it", "ita2", 3.0, "#FFFFFF", "#E30613"),
  _xc("cre", "Cremonese", "Cremona", "it", "ita2", 2.9, "#E30613", "#999999"),
  _xc("parm", "Parma", "Parma", "it", "ita2", 3.2, "#FFE200", "#0033A0"),
  _xc("wlf", "Wolfsburg", "Wolfsburg", "de", "ger2", 3.2, "#65B32E", "#FFFFFF"),
  _xc("bmg", "Gladbach", "Mönchengladbach", "de", "ger", 3.8, "#000000", "#FFFFFF"),
  _xc("fre", "Freiburg", "Freiburg", "de", "ger", 3.8, "#000000", "#E30613"),
  _xc("hof", "Hoffenheim", "Sinsheim", "de", "ger", 3.7, "#1C63B7", "#FFFFFF"),
  _xc("renn", "Rennes", "Rennes", "fr", "fra", 3.8, "#E20E0E", "#000000"),
  _xc("len", "Lens", "Lens", "fr", "fra", 3.8, "#E30613", "#FCDD09"),
  _xc("str", "Strasbourg", "Estrasburgo", "fr", "fra", 3.6, "#009FE3", "#E30613"),
  _xc("nte", "Nantes", "Nantes", "fr", "fra2", 2.9, "#FFE200", "#00A651"),
  _xc("bra", "Braga", "Braga", "pt", "por", 3.8, "#E30613", "#FFFFFF"),
  _xc("vgu", "Vitória Guimarães", "Guimarães", "pt", "por", 3.4, "#FFFFFF", "#000000"),
  _xc("az", "AZ Alkmaar", "Alkmaar", "nl", "ned", 3.6, "#ED1C24", "#FFFFFF"),
  _xc("twt", "Twente", "Enschede", "nl", "ned", 3.5, "#E2001A", "#FFFFFF"),
  _xc("clb", "Club Brugge", "Bruges", "be", "bel", 3.9, "#0070B8", "#000000"),
  _xc("and", "Anderlecht", "Bruxelas", "be", "bel", 3.5, "#5A2D81", "#FFFFFF"),
  _xc("gal", "Galatasaray", "Istambul", "tr", "tur", 3.9, "#FDB912", "#A32521"),
  _xc("fen", "Fenerbahçe", "Istambul", "tr", "tur", 3.8, "#002F6C", "#FFED00"),
  _xc("cel", "Celtic", "Glasgow", "sct", "sco", 3.6, "#018749", "#FFFFFF"),
  _xc("ran", "Rangers", "Glasgow", "sct", "sco", 3.6, "#054C9E", "#FFFFFF"),
  _xc("gnk", "Genk", "Genk", "be", "bel", 3.6, "#1B4F9C", "#FFFFFF"),
  _xc("bjk", "Beşiktaş", "Istambul", "tr", "tur", 3.7, "#000000", "#FFFFFF"),
  _xc("abd", "Aberdeen", "Aberdeen", "sct", "sco", 3.2, "#E30613", "#FFFFFF"),
  _xc("cco", "Colo-Colo", "Santiago", "cl", "chi", 3.5, "#FFFFFF", "#000000"),
  _xc("ude", "Universidad de Chile", "Santiago", "cl", "chi", 3.3, "#0033A0", "#FFFFFF"),
  _xc("ucat", "Universidad Católica", "Santiago", "cl", "chi", 3.3, "#0033A0", "#FFFFFF"),
  _xc("bsc", "Barcelona SC", "Guayaquil", "ec", "ecu", 3.0, "#FFD100", "#0033A0"),
  _xc("ldu", "LDU Quito", "Quito", "ec", "ecu", 3.1, "#FFFFFF", "#0033A0"),
  _xc("eme", "Emelec", "Guayaquil", "ec", "ecu", 2.9, "#0033A0", "#FFFFFF"),
  _xc("olp", "Olimpia", "Assunção", "py", "par", 3.1, "#FFFFFF", "#000000"),
  _xc("cpo", "Cerro Porteño", "Assunção", "py", "par", 3.0, "#CE1126", "#0033A0"),
  _xc("lbt", "Libertad", "Assunção", "py", "par", 2.9, "#FFFFFF", "#000000"),
  _xc("dzg", "Dinamo Zagreb", "Zagreb", "hr", "hnl", 3.6, "#0033A0", "#FFFFFF"),
  _xc("haj", "Hajduk Split", "Split", "hr", "hnl", 3.3, "#FFFFFF", "#0033A0"),
  _xc("rij", "Rijeka", "Rijeka", "hr", "hnl", 3.2, "#FFFFFF", "#0033A0"),
  _xc("oly", "Olympiacos", "Pireu", "gr", "slg", 3.6, "#CE1126", "#FFFFFF"),
  _xc("pao", "Panathinaikos", "Atenas", "gr", "slg", 3.4, "#007A33", "#FFFFFF"),
  _xc("aek", "AEK Atenas", "Atenas", "gr", "slg", 3.3, "#FFD100", "#000000"),
  _xc("zen", "Zenit", "São Petersburgo", "ru", "rpl", 3.8, "#00A0E3", "#FFFFFF"),
  _xc("spm", "Spartak Moscou", "Moscou", "ru", "rpl", 3.6, "#CE1126", "#FFFFFF"),
  _xc("csk", "CSKA Moscou", "Moscou", "ru", "rpl", 3.5, "#CE1126", "#0033A0"),
  _xc("wyd", "Wydad", "Casablanca", "ma", "bot", 2.9, "#CE1126", "#FFFFFF"),
  _xc("rca", "Raja Casablanca", "Casablanca", "ma", "bot", 2.8, "#007A33", "#FFFFFF"),
  _xc("asfr", "FAR Rabat", "Rabat", "ma", "bot", 2.6, "#CE1126", "#007A33"),
  _xc("uls", "Ulsan HD", "Ulsan", "kr", "kle", 3.3, "#0033A0", "#FFFFFF"),
  _xc("jhb", "Jeonbuk", "Jeonju", "kr", "kle", 3.2, "#007A33", "#FFD100"),
  _xc("fcs", "FC Seoul", "Seul", "kr", "kle", 3.1, "#CE1126", "#000000"),
  _xc("cvy", "Cavalry FC", "Calgary", "ca", "cpl", 2.8, "#CE1126", "#FFFFFF"),
  _xc("ato", "Atlético Ottawa", "Ottawa", "ca", "cpl", 2.7, "#CE1126", "#000000"),
  _xc("pfc", "Pacific FC", "Victoria", "ca", "cpl", 2.6, "#5C2D91", "#2EC4B6")
]);

/* League trophy / cup mapping — proper names via TROPHIES ids */
(function patchLeagueTrophies() {
  var map = {
    bra: { trophy: "brasileirao", cupTrophy: "copa_br" },
    brb: { trophy: "serie_b", cupTrophy: "copa_br" },
    arg: { trophy: "ligapro", cupTrophy: "copa_arg" },
    uru: { trophy: "uruprimera", cupTrophy: "copa_uy" },
    col: { trophy: "colbetplay", cupTrophy: "copa_col" },
    mex: { trophy: "liga_mx", cupTrophy: "copa_mx" },
    por: { trophy: "primerliga", cupTrophy: "taca_pt" },
    esp: { trophy: "laliga", cupTrophy: "copa_rey" },
    eng: { trophy: "premier", cupTrophy: "fa_cup" },
    fra: { trophy: "ligue1", cupTrophy: "coupe_fr" },
    ita: { trophy: "seriea", cupTrophy: "coppa_ita" },
    ger: { trophy: "bundesliga", cupTrophy: "dfb_pokal" },
    ned: { trophy: "eredivisie", cupTrophy: "knvb" },
    usa: { trophy: "mls", cupTrophy: "us_open" },
    jpn: { trophy: "j1", cupTrophy: "emperor" },
    nga: { trophy: "npfl", cupTrophy: "copa_ng" },
    sen: { trophy: "senliga", cupTrophy: "copa_sn" },
    bel: { trophy: "proleague", cupTrophy: "copa_be" },
    tur: { trophy: "superlig", cupTrophy: "copa_tr" },
    sco: { trophy: "scottish", cupTrophy: "scottish_cup" },
    chi: { trophy: "primera_cl", cupTrophy: "copa_cl" },
    ecu: { trophy: "liga_ec", cupTrophy: "copa_ec" },
    par: { trophy: "primera_py", cupTrophy: "copa_py" },
    /* Hrvatski kup: no free clean trophy cutout — cupTrophy false skips the generic copa fallback */
    hnl: { trophy: "hnl", cupTrophy: false },
    slg: { trophy: "slgreece", cupTrophy: "greek_cup" },
    rpl: { trophy: "rpl", cupTrophy: "russian_cup" },
    bot: { trophy: "botola", cupTrophy: "trone" },
    kle: { trophy: "kleague", cupTrophy: "korea_cup" },
    cpl: { trophy: "cpl", cupTrophy: "can_champ" },
    brc: { trophy: "serie_c", cupTrophy: "copa_br" },
    eng2: { trophy: "championship", cupTrophy: "fa_cup" },
    ger2: { trophy: "bundesliga2", cupTrophy: "dfb_pokal" },
    fra2: { trophy: "ligue2", cupTrophy: "coupe_fr" },
    esp2: { trophy: "segunda", cupTrophy: "copa_rey" },
    ita2: { trophy: "serie_b_ita", cupTrophy: "coppa_ita" }
  };
  for (var i = 0; i < LEAGUES.length; i++) {
    var m = map[LEAGUES[i].id];
    if (!m) continue;
    LEAGUES[i].trophy = m.trophy;
    LEAGUES[i].cupTrophy = m.cupTrophy;
  }
})();

/* Lower-tier / extra clubs so thin nations always have ≥3 academy options */
CLUBS = CLUBS.concat([
  _xc("dan", "Danubio", "Montevidéu", "uy", "uru", 2.6, "#000000", "#FFFFFF"),
  _xc("rivu", "River Plate UY", "Montevidéu", "uy", "uru", 2.5, "#CE1126", "#FFFFFF"),
  _xc("jun", "Junior", "Barranquilla", "co", "col", 3.0, "#CE1126", "#FFFFFF"),
  _xc("dep", "Deportivo Cali", "Cali", "co", "col", 2.9, "#007A33", "#FFFFFF"),
  _xc("tol", "Toluca", "Toluca", "mx", "mex", 3.4, "#CE1126", "#FFFFFF"),
  _xc("paz", "Cruz Azul", "Cidade do México", "mx", "mex", 3.5, "#0033A0", "#FFFFFF"),
  _xc("sea", "Seattle Sounders", "Seattle", "us", "usa", 3.1, "#5D9732", "#0033A0"),
  _xc("nyc", "NYCFC", "Nova York", "us", "usa", 3.0, "#6CACE4", "#00285E"),
  _xc("kaw", "Kawasaki Frontale", "Kawasaki", "jp", "jpn", 3.0, "#87CEEB", "#000080"),
  _xc("cer", "Cerezo Osaka", "Osaka", "jp", "jpn", 2.8, "#CE1126", "#FF69B4"),
  _xc("rvs", "Rivers United", "Port Harcourt", "ng", "nga", 2.2, "#0033A0", "#FFFFFF"),
  _xc("ranfc", "Rangers Int'l", "Enugu", "ng", "nga", 2.1, "#FFD700", "#0033A0"),
  _xc("gen", "Génération Foot", "Dakar", "sn", "sen", 2.0, "#00853F", "#E31C23"),
  _xc("ouc", "US Ouakam", "Dakar", "sn", "sen", 1.9, "#FFFFFF", "#00853F"),
  _xc("hur", "Huracán", "Buenos Aires", "ar", "arg", 3.2, "#FFFFFF", "#CE1126"),
  _xc("vel", "Vélez", "Buenos Aires", "ar", "arg", 3.4, "#FFFFFF", "#0033A0"),
  _xc("gio", "Náutico", "Recife", "br", "brb", 2.3, "#0033A0", "#FFFFFF"),
  _xc("csa", "CSA", "Maceió", "br", "brc", 2.1, "#0033A0", "#FFFFFF"),

  /* --- synced Brasileirão 2026 (Série A promoted / missing) --- */
  _xc("mir", "Mirassol", "Mirassol", "br", "bra", 3.2, "#FFD100", "#0066B3"),
  _xc("vit", "Vitória", "Salvador", "br", "bra", 3.3, "#E31837", "#000000"),
  _xc("ctb", "Coritiba", "Curitiba", "br", "bra", 3.3, "#007A33", "#FFFFFF"),
  _xc("chp", "Chapecoense", "Chapecó", "br", "bra", 3.1, "#007A33", "#FFFFFF"),
  _xc("rem", "Remo", "Belém", "br", "bra", 3.0, "#0033A0", "#FFFFFF"),

  /* --- synced Brasileirão Série B 2026 --- */
  _xc("jve", "Juventude", "Caxias do Sul", "br", "brb", 2.9, "#007A33", "#FFFFFF"),
  _xc("lon", "Londrina", "Londrina", "br", "brb", 2.5, "#0033A0", "#FFFFFF"),
  _xc("sbe", "São Bernardo", "São Bernardo", "br", "brb", 2.5, "#FFD100", "#000000"),
  _xc("cri", "Criciúma", "Criciúma", "br", "brb", 2.7, "#FFD100", "#000000"),
  _xc("nov", "Novorizontino", "Novo Horizonte", "br", "brb", 2.6, "#FFD100", "#000000"),
  _xc("crb", "CRB", "Maceió", "br", "brb", 2.6, "#E31837", "#FFFFFF"),
  _xc("cui", "Cuiabá", "Cuiabá", "br", "brb", 2.7, "#007A33", "#FFD100"),
  _xc("ago", "Atlético-GO", "Goiânia", "br", "brb", 2.7, "#E31837", "#000000"),
  _xc("ope", "Operário-PR", "Ponta Grossa", "br", "brb", 2.5, "#000000", "#FFFFFF"),
  _xc("vna", "Vila Nova", "Goiânia", "br", "brb", 2.5, "#E31837", "#FFFFFF"),
  _xc("amg", "América-MG", "Belo Horizonte", "br", "brb", 2.8, "#007A33", "#000000"),
  _xc("athm", "Athletic-MG", "São João del-Rei", "br", "brb", 2.4, "#000000", "#FFFFFF"),
  _xc("bsp", "Botafogo-SP", "Ribeirão Preto", "br", "brb", 2.5, "#E31837", "#000000"),

  /* --- Premier League 2026/27 (promoted + missing top-flight) --- */
  _xc("cov", "Coventry", "Coventry", "en", "eng", 3.5, "#77C7F2", "#FFFFFF"),
  _xc("ips", "Ipswich", "Ipswich", "en", "eng", 3.6, "#0033A0", "#FFFFFF"),
  _xc("hul", "Hull City", "Hull", "en", "eng", 3.5, "#F5A12D", "#000000"),
  _xc("bou", "Bournemouth", "Bournemouth", "en", "eng", 3.7, "#DA291C", "#000000"),
  _xc("bre", "Brentford", "Londres", "en", "eng", 3.8, "#E30613", "#FFFFFF"),
  _xc("lee", "Leeds", "Leeds", "en", "eng", 3.8, "#FFFFFF", "#1D355E"),
  _xc("sun", "Sunderland", "Sunderland", "en", "eng", 3.6, "#E30613", "#FFFFFF"),

  /* --- Bundesliga 2026/27 promoted --- */
  _xc("s04", "Schalke", "Gelsenkirchen", "de", "ger", 3.6, "#004D95", "#FFFFFF"),
  _xc("elv", "Elversberg", "Elversberg", "de", "ger", 3.2, "#FFFFFF", "#000000"),
  _xc("pad", "Paderborn", "Paderborn", "de", "ger", 3.3, "#005CA9", "#FFFFFF"),

  /* --- Ligue 1 2026/27 promoted --- */
  _xc("tro", "Troyes", "Troyes", "fr", "fra", 3.2, "#0033A0", "#FFFFFF"),
  _xc("lem", "Le Mans", "Le Mans", "fr", "fra", 3.1, "#E30613", "#FFD100"),

  /* --- pack 1: 2026-27 top flight (Scotland, HNL, CPL, Botola) --- */
  _xc("hrt", "Hearts", "Edinburgh", "sct", "sco", 3.4, "#7A003C", "#FFFFFF"),
  _xc("hib", "Hibernian", "Edinburgh", "sct", "sco", 3.3, "#007A33", "#FFFFFF"),
  _xc("mot", "Motherwell", "Motherwell", "sct", "sco", 3.2, "#6C1D45", "#F5B335"),
  _xc("dun", "Dundee", "Dundee", "sct", "sco", 3.1, "#132257", "#FFFFFF"),
  _xc("duu", "Dundee United", "Dundee", "sct", "sco", 3.1, "#F15A22", "#000000"),
  _xc("kil", "Kilmarnock", "Kilmarnock", "sct", "sco", 3.0, "#0033A0", "#FFFFFF"),
  _xc("stm", "St Mirren", "Paisley", "sct", "sco", 3.0, "#000000", "#FFFFFF"),
  _xc("fal", "Falkirk", "Falkirk", "sct", "sco", 3.0, "#001F5B", "#FFFFFF"),
  _xc("sjo", "St Johnstone", "Perth", "sct", "sco", 2.9, "#003DA5", "#FFFFFF"),

  _xc("var", "Varaždin", "Varaždin", "hr", "hnl", 3.2, "#0033A0", "#FFFFFF"),
  _xc("osi", "Osijek", "Osijek", "hr", "hnl", 3.1, "#0057A8", "#FFFFFF"),
  _xc("lok", "Lokomotiva", "Zagreb", "hr", "hnl", 3.0, "#0033A0", "#FFFFFF"),
  _xc("ist", "Istra 1961", "Pula", "hr", "hnl", 3.0, "#007A33", "#FFE500"),
  _xc("gor", "Gorica", "Velika Gorica", "hr", "hnl", 2.9, "#0057B8", "#FFFFFF"),
  _xc("slb", "Slaven Belupo", "Koprivnica", "hr", "hnl", 2.9, "#0033A0", "#FFFFFF"),
  _xc("rud", "Rudeš", "Zagreb", "hr", "hnl", 2.8, "#003DA5", "#FFFFFF"),

  _xc("frg", "Forge FC", "Hamilton", "ca", "cpl", 2.9, "#F26522", "#111111"),
  _xc("vfc", "Vancouver FC", "Langley", "ca", "cpl", 2.6, "#212322", "#FFFFFF"),
  _xc("hfx", "HFX Wanderers", "Halifax", "ca", "cpl", 2.5, "#00205B", "#6EC1E4"),
  _xc("itr", "Inter Toronto", "Toronto", "ca", "cpl", 2.5, "#0A2342", "#C4A35A"),
  _xc("sup", "Supra du Québec", "Laval", "ca", "cpl", 2.4, "#E10600", "#002D72"),

  _xc("masf", "MAS Fez", "Fez", "ma", "bot", 3.0, "#F5D000", "#111111"),
  _xc("rsb", "RS Berkane", "Berkane", "ma", "bot", 2.8, "#F36C21", "#111111"),
  _xc("fus", "FUS Rabat", "Rabat", "ma", "bot", 2.7, "#C8102E", "#FFFFFF"),
  _xc("husa", "Hassania Agadir", "Agadir", "ma", "bot", 2.6, "#C8102E", "#FFFFFF"),
  _xc("irt", "Ittihad Tanger", "Tanger", "ma", "bot", 2.6, "#0057B8", "#FFFFFF"),
  _xc("codm", "CODM Meknès", "Meknès", "ma", "bot", 2.5, "#E10600", "#FFFFFF"),
  _xc("dhj", "Difaâ El Jadida", "El Jadida", "ma", "bot", 2.5, "#007A33", "#FFFFFF"),
  _xc("kacm", "Kawkab Marrakech", "Marrakech", "ma", "bot", 2.4, "#C8102E", "#FFFFFF"),
  _xc("uts", "Union Touarga", "Rabat", "ma", "bot", 2.4, "#F5C518", "#111111"),
  _xc("mat", "MA Tétouan", "Tétouan", "ma", "bot", 2.3, "#C8102E", "#FFFFFF"),
  _xc("rcaz", "RCA Zemamra", "Zemamra", "ma", "bot", 2.3, "#0057B8", "#FFFFFF"),
  _xc("usat", "Amal Tiznit", "Tiznit", "ma", "bot", 2.2, "#0057B8", "#FFFFFF"),
  _xc("wst", "Widad Témara", "Témara", "ma", "bot", 2.1, "#C8102E", "#0033A0"),

  /* --- pack 2: 2026-27 top flight (Belgium, Chile, Greece, Korea) --- */
  _xc("usg", "Union SG", "Bruxelas", "be", "bel", 3.8, "#FFE000", "#000055"),
  _xc("gnt", "Gent", "Gante", "be", "bel", 3.6, "#0023DD", "#FFFFFF"),
  _xc("ant", "Antwerp", "Antuérpia", "be", "bel", 3.5, "#FF0000", "#FFFFFF"),
  _xc("std", "Standard Liège", "Liège", "be", "bel", 3.5, "#DD0000", "#FFFFFF"),
  _xc("mec", "Mechelen", "Mechelen", "be", "bel", 3.4, "#FFD700", "#000000"),
  _xc("cha", "Charleroi", "Charleroi", "be", "bel", 3.4, "#000000", "#FFFFFF"),
  _xc("ceb", "Cercle Brugge", "Bruges", "be", "bel", 3.3, "#00852D", "#000000"),
  _xc("stvv", "Sint-Truiden", "Sint-Truiden", "be", "bel", 3.3, "#FFFF00", "#0000FF"),
  _xc("wes", "Westerlo", "Westerlo", "be", "bel", 3.3, "#FFFF00", "#0000FF"),
  _xc("ohl", "OH Leuven", "Lovaina", "be", "bel", 3.2, "#E10600", "#007A33"),
  _xc("zwa", "Zulte Waregem", "Waregem", "be", "bel", 3.2, "#FF0026", "#009640"),
  _xc("louv", "La Louvière", "La Louvière", "be", "bel", 3.1, "#009150", "#FFFFFF"),
  _xc("kor", "Kortrijk", "Kortrijk", "be", "bel", 3.0, "#FF0000", "#FFFFFF"),
  _xc("lom", "Lommel", "Lommel", "be", "bel", 2.9, "#009150", "#FFFFFF"),
  _xc("bev", "Beveren", "Beveren", "be", "bel", 2.9, "#F5C518", "#0033A0"),

  _xc("coq", "Coquimbo Unido", "Coquimbo", "cl", "chi", 3.4, "#FFDE00", "#000000"),
  _xc("evcl", "Everton Viña", "Viña del Mar", "cl", "chi", 3.3, "#003159", "#FFD100"),
  _xc("plst", "Palestino", "Santiago", "cl", "chi", 3.3, "#007A33", "#FFFFFF"),
  _xc("hua", "Huachipato", "Talcahuano", "cl", "chi", 3.2, "#0000FF", "#000000"),
  _xc("aud", "Audax Italiano", "Santiago", "cl", "chi", 3.2, "#1C9E1C", "#FFFFFF"),
  _xc("nub", "Ñublense", "Chillán", "cl", "chi", 3.2, "#FF0000", "#FFFFFF"),
  _xc("lim", "Deportes Limache", "Limache", "cl", "chi", 3.1, "#D5303E", "#000000"),
  _xc("dls", "La Serena", "La Serena", "cl", "chi", 3.1, "#B20837", "#FFFFFF"),
  _xc("ohig", "O'Higgins", "Rancagua", "cl", "chi", 3.1, "#83CCF9", "#FFFFFF"),
  _xc("cob", "Cobresal", "El Salvador", "cl", "chi", 3.0, "#F36C21", "#000000"),
  _xc("ulc", "Unión La Calera", "La Calera", "cl", "chi", 3.0, "#EE0000", "#FFFFFF"),
  _xc("udec", "Universidad de Concepción", "Concepción", "cl", "chi", 2.9, "#FFFF00", "#010633"),
  _xc("dcon", "Deportes Concepción", "Concepción", "cl", "chi", 2.8, "#5C4AB0", "#FFFFFF"),

  _xc("paok", "PAOK", "Tessalônica", "gr", "slg", 3.5, "#000000", "#FFFFFF"),
  _xc("ari", "Aris", "Tessalônica", "gr", "slg", 3.3, "#FFD100", "#000000"),
  _xc("ofi", "OFI", "Heraclião", "gr", "slg", 3.2, "#000000", "#FFFFFF"),
  _xc("atro", "Atromitos", "Atenas", "gr", "slg", 3.1, "#0033A0", "#FFFFFF"),
  _xc("ast", "Asteras Tripolis", "Trípoli", "gr", "slg", 3.1, "#FFD100", "#0033A0"),
  _xc("vol", "Volos", "Volos", "gr", "slg", 3.0, "#FF0000", "#0033A0"),
  _xc("kif", "Kifisia", "Kifisia", "gr", "slg", 3.0, "#002147", "#FFFFFF"),
  _xc("lvk", "Levadiakos", "Livadeia", "gr", "slg", 3.0, "#005754", "#FFFFFF"),
  _xc("pnt", "Panetolikos", "Agrinio", "gr", "slg", 2.9, "#FFEA00", "#0033A0"),
  _xc("irk", "Iraklis", "Tessalônica", "gr", "slg", 2.8, "#000066", "#FFFFFF"),
  _xc("kal", "Kalamata", "Kalamata", "gr", "slg", 2.7, "#000000", "#FFFFFF"),

  _xc("poh", "Pohang Steelers", "Pohang", "kr", "kle", 3.3, "#C8102E", "#000000"),
  _xc("jsk", "Jeju SK", "Seogwipo", "kr", "kle", 3.1, "#EC6B32", "#FFFFFF"),
  _xc("gwn", "Gangwon FC", "Chuncheon", "kr", "kle", 3.1, "#F53A45", "#000000"),
  _xc("dhc", "Daejeon Hana", "Daejeon", "kr", "kle", 3.0, "#007854", "#FFFFFF"),
  _xc("icu", "Incheon United", "Incheon", "kr", "kle", 3.0, "#0000FF", "#000000"),
  _xc("any", "FC Anyang", "Anyang", "kr", "kle", 2.9, "#4B1D80", "#171715"),
  _xc("gmc", "Gimcheon Sangmu", "Gimcheon", "kr", "kle", 2.8, "#FF0000", "#000000"),
  _xc("buc", "Bucheon FC", "Bucheon", "kr", "kle", 2.7, "#FF0000", "#000000"),
  _xc("gwj", "Gwangju FC", "Gwangju", "kr", "kle", 2.6, "#EDBA23", "#641C20")
]);
